### ISSUE TITLE
ask for a guide

### ISSUE THREAD

**Issue by goog** [timvieira/crf#1]
Hey,pal ! I wanna program the crf in python,but I still diidn't understand it and being puzzled. Could you send me some tutorials of CRF or tell me how to learn it please? Any guidance would be greatly appreciated! Thanks in advance!

**Comment by bboalimoe** [comment]
hello, i know that hmm can predict the label of one observed sequence such as predict the word of one speech.can crf do the same thing ...the steps are like: 
1.first train the different crf models with diffenrent set of  samples
2.input the sequence that want predicting to different models and get the probabilities of diffenrent models 
3.find the model that has the maximum probability,and the label the sequence with the model's label.

thanks a lot!

**Comment by Malkitti** [comment]
http://cseweb.ucsd.edu/~elkan/250Bwinter2012/loglinearCRFs.pdf - This document could be useful to understand mathematics and basics.  Furthermore,  you could watch  this video-  http://videolectures.net/cikm08_elkan_llmacrf/
