### ISSUE TITLE
Question about feature function

### ISSUE THREAD

**Issue by FanfanYoung** [timvieira/crf#10]
Hi, I'm confused about the feature function. In your code, is feature function defined in the method FeatureVectorSequence?

**Comment by timvieira** [comment]
The features you are (probably) looking for are not in `FeatureVectorSequence`. Have a look at the example application in `example.py`, in particular [line 43](https://github.com/timvieira/crf/blob/master/crf/example.py#L43), which defines a function called `token_features`.
