### ISSUE TITLE
How to process the third-party data?

### ISSUE THREAD

**Issue by fooSynaptic** [timvieira/crf#13]
I think the tagged_reference.txt is the math reference data from https://people.cs.umass.edu/~mccallum/data/cora-refs.tar.gz, i am wondering whether the data need process or the script can run with raw data?

**Comment by timvieira** [comment]
I have provided a version of the data already. It is probably identical to the one you linked to but I haven't checked. You could diff the two files.

All of the processing is in the training script.

**Comment by fooSynaptic** [comment]
Thank you, i havnot notice the `data` path, they looks like identical

**Comment by fooSynaptic** [comment]
And one more question, is there some blog or material about the CRF implementation from scrath?

**Comment by timvieira** [comment]
I have a [blog post on CRFs](https://timvieira.github.io/blog/post/2015/04/29/multiclass-logistic-regression-and-conditional-random-fields-are-the-same-thing/) which may have some useful references for you.

**Comment by fooSynaptic** [comment]
Appreciate your work, thanks
