### ISSUE TITLE
Potential bug

### ISSUE THREAD

**Issue by braingineer** [timvieira/crf#5]
Hi Tim,

I was using your code as a base for a course homework I'm TAing.  

I was looking at your forward code and I was wondering if you had a rationale for how you use the logexpsum.  

Looking at Sutton & McCallum [1] and taking alpha as forward recursion variable, it seems that each forward recursion is:

alpha(thisstate) = sum_laststate exp(transition_potential)*alpha(laststate)

You are adding the alpha(laststate) to the transition potential, exponentiating, summing, and logging (and some interesting max operator thing going on).  

Can you really combine the alpha and transition in the exponential?  I don't see how you push an exponential function back to the outside in each alpha to allow for such an operation.  

Thanks!

[1] Sutton & McCallum. Page 15. Section 1.3.3.  Eq. 1.37. http://people.cs.umass.edu/~mccallum/papers/crf-tutorial.pdf 

(side note, I believe we met at MASC this year)

Best,
Brian

**Comment by timvieira** [comment]
The difference you see v. Sutton and McCallum has to do with the fact that I am computing log-alpha / log-beta. This is a very common way to implement any probability calculations. We do it because if you multiply lots of numbers between 0 and 1 they will get extremely small very quickly. Log-probabilities on the other hand, don't have this problem.

When you compute in log space, operators change: + -> logsumexp, * -> +, 0 -> -infinity, 1 -> 0. (Yeah, pretty confusing at first.)

    log(a*b + c*d) = logsumexp(log(a) + log(b), log(c) + log(d))

where logsumexp(a, b) = log(exp(a) + log(b))

The implementation of logsumexp uses another trick known as "the log-exp-exp trick" --- that's where the max comes from.

These are very common tricks. You should probably include them in your course because they are important for implementation. Usually students learn to compute probabilities in log-space when they implement naive Bayes.

I recognize your name. You gave the talk on Bayesian colors, right?

**Comment by braingineer** [comment]
Hi Tim,

Thanks for the response!

Ahh. 

I'm familiar with the standard log trick.. I don't think you can do machine learning without it. 

The log-sum-exp and log-exp-exp tricks I haven't seen before, though.  Do you have any references for the log-exp-exp?  A quick google search for "log exp exp" (or logexpexp)  doesn't turn up very much.   

The logsumexp is basically [this](http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.misc.logsumexp.html) right?  I found [this](https://hips.seas.harvard.edu/blog/2013/01/09/computing-log-sum-exp/) for the max trick.  This hadn't been taught in my ML courses so I'm glad I came across it in your stuff!  I've never worked with sequential or log linear models before (or really, too much implementation beyond theoretical justifications), so I hadn't come across this.  It's a fantastic trick and I will definitely be including it in the homework set. 

So, I knew that it needed log(p(x)) and thus the log alphas, but I didn't understand how the log was getting pushed into each alpha term. I.e., how you were able to take logsumexp of each alpha, and the combine it with the next set of edge potentials in the exp operator.  But I worked out my confusion:
```
simplifying to just alpha(i):
alpha(i) = sum_k weight_k * feat_k (i)
log(sum(exp(alpha(1))* sum(exp(alpha(0)))) 
= log ( sum(exp(alpha(1)) *exp( log(sum(exp(alpha(0)))))) 
```
and then do the exp combinations from there.  So, the exp(log()) in each term had alluded me last night for some reason.

Anyway, thanks again for your response! It was greatly appreciated =). 

Also, yep! That was me.  I think we'll both be at NAACL too (I saw you had a TACL paper as well and I'm assuming you'll be presenting it there).   I'll be sure to try to say hello (and thanks again, haha).

All the best, 
Brian

**Comment by timvieira** [comment]
> I'm familiar with the standard log trick.. I don't think you can do
machine learning without it.

Cool. Log add is a natural extension for when you have a sum as well as a
product.

> The log-sum-exp and log-exp-exp tricks I haven't seen before, though. Do
you have any references for the log-exp-exp? A quick google search for "log
exp exp" (or logexpexp) doesn't turn up very much.

Sorry, "log-exp-exp" is a typo.

> The logsumexp is basically this right? I found this for the max trick.

That's a good post. I like Ryan Adams' and his group a lot.

You might also be interested in the "semiring" abstraction. Another "trick"
you'll see in nlp algorithms. This keys you use the same code for Viterbi
and the forward algorithm, as well as many others e.g. enumerating/counting
derivations/paths, k-best lists.

> This hadn't been taught in my ML courses so I'm glad I came across it in
your stuff! I've never worked with sequential or log linear models before
(or really, too much implementation beyond theoretical justifications), so
I hadn't come across this. It's a fantastic trick and I will definitely be
including it in the homework set.

Btw, logsumexp is also known as "soft max."

I have a few of these things and similarones on my blog
http://timvieira.github.io/blog

Similar tricks can be used to avoid overflow when computing the sigmoid
function (is just log(sigmoid (x))=logsumexp(0, x)) as well as p-norms.

> So, I knew that it needed log(p(x)) and thus the log alphas, but I didn't
understand how the log was getting pushed into each alpha term. I.e., how
you were able to take logsumexp of each alpha, and the combine it with the
next set of edge potentials in the exp operator. But I worked out my
confusion:
>
> simplifying to just alpha(i):
> alpha(i) = sum_k weight_k * feat_k (i)
> log(sum(exp(alpha(1))* sum(exp(alpha(0))))
> = log ( sum(exp(alpha(1)) *exp( log(sum(exp(alpha(0))))))
>
> and then do the exp combinations from there. So, the exp(log()) in each
term had alluded me last night for some reason.

Sound right :-)

> Anyway, thanks again for your response! It was greatly appreciated =).

No problem. Happy to help!

> Also, yep! That was me. I think we'll both be at NAACL too (I saw you had
a TACL paper as well and I'm assuming you'll be presenting it there). I'll
be sure to try to say hello (and thanks again, haha).

I wasn't planning on presenting it. Some I'mserving author. But, maybe it's
not a terrible idea.

Good luck with the TAing!
