### ISSUE TITLE
can crf predict like hmm

### ISSUE THREAD

**Issue by bboalimoe** [timvieira/crf#6]
hello, i know that hmm can predict the label of one observed sequence such as predict the word of one speech.can crf do the same thing ...the steps are like: 
1.first train the different crf models with diffenrent set of samples
2.input the sequence that want predicting to different models and get the probabilities of diffenrent models 
3.find the model that has the maximum probability,and the label the sequence with the model's label.

thanks a lot!

**Comment by braingineer** [comment]
you have described viterbi labeling. yes, CRFs can do that.  Viterbi is a method for learning the maximally likely path through the hidden states. 

I am 80% positive on the following statement: What the CRF can't do is be generative.  Given a sequence, you can't sample from the states (x from y).

**Comment by bboalimoe** [comment]
maybe what i mean is not the viterbi.....for  i don't care about the real values of hidden states. i just want to train several models and use the forward algo to get the likehood .  i know that crf is descriminal model~ i just want to the get the label of one sequence ,not the label of every object of one sequence. thanks ~`

**Comment by braingineer** [comment]
I'm not sure what you mean for label of one sequence.  Let's take as an example either the [umbrella example](http://web.engr.oregonstate.edu/~tgd/classes/430/slides/part7.pdf) or part of speech tagging (each hidden label is a part of speech tag, each emission token is a word).  What is it you  mean to refer to?

**Comment by bboalimoe** [comment]
it is this problem:
(1)The Evaluation Problem
Given an HMM  model lambda and a sequence of observations  what is the probability that the observations are generated by the model.
=======
and i would like to know if crf can give the probability of one sequence? so we can compare different trained crf models to the get the highest probable model~~
thansk a lot~
