### ISSUE TITLE
how to run it?

### ISSUE THREAD

**Issue by andyyuan78** [timvieira/crf#7]
ubgpu@ubgpu:~/github/crf$ python example.py run 100
Traceback (most recent call last):
  File "example.py", line 138, in <module>
    main(proportion=[0.7, 0.3], iterations=args.interations)
AttributeError: 'Namespace' object has no attribute 'interations'
ubgpu@ubgpu:~/github/crf$ echo $PYTHONPATH
/home/ubgpu/github/arsenal:/usr/local/lib/python2.7/dist-packages
ubgpu@ubgpu:~/github/crf$

**Comment by timvieira** [comment]
Sorry about that. It was a silly bug. Apparently, I've only been testing the "quick" versions.
