### ISSUE TITLE
Potential bug with parameter matrix[W] initialization

### ISSUE THREAD

**Issue by dongnanzhy** [timvieira/crf#8]
Hi, After we done some experiment, we found that, In stringcrf2.py the size of W (crf feature function parameter matrix) should be (A+L)*L instead of A*L. After fixing size issue and a related line of code, we can achieve higher llh on same dataset and also monotonically increase after iteration. However, it could be highly possible that we are wrong, so please check that. We are looking forward to hear from you, thanks

**Comment by timvieira** [comment]
Good catch! Your suggested fix is correct.

Thank you!
